# Config dedicated for module B
# All the resources must be prefixed with `module-b-` to avoid conflicts

version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    parameters:
      app-dir:
        default: '~/project/module-python'
        type: string
      reports-dir: 
        default: '~/project/module-python/dist/reports'
        type: string
    steps:
      - checkout
      - run: 
          name: Show python version
          command: python --version
      - run:
          name: Install PDM
          command: pip install --user pdm
      - run:
          name: Download Dependencies
          command: cd << parameters.app-dir >> && pdm install
      - run: 
          name: Unit Testing
          command: cd << parameters.app-dir >> && pdm run test
      - store_test_results: 
          path: << parameters.reports-dir >>

workflows:
  module_python_test:
    jobs:
      - test


