# Config dedicated for module B
# All the resources must be prefixed with `module-b-` to avoid conflicts

version: 2.1

orbs:
  maven: circleci/maven@1.4.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:21.0.0
    parameters:
      app-dir:
        default: '~/project/module-java'
        type: string
    steps:
      - checkout
      - run: 
          name: Show java version
          command: java --version
      - run: 
          name: Unit Testing
          command: cd << parameters.app-dir >> && ./mvnw test
      - store_test_results: 
          path: << parameters.app-dir >>/target/surefire-reports

workflows:
  module_java_test:
    jobs:
      - test


