# Config dedicated for module B
# All the resources must be prefixed with `module-b-` to avoid conflicts

version: 2.1

parameters:
  publish-module:
    description: Publish a specific module
    type: string
    default: ""
  publish-module-version:
    description: Version to publish the module
    type: string
    default: ""

jobs:
  checkout:
    docker:
      - image: cimg/openjdk:21.0.0
    steps:
      - checkout
      - run: 
          name: Show java version
          command: java --version
      # Adding downloaded source code to workspace 
      # in order to pass it to other jobs and
      # prevent having to download it again
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: cimg/openjdk:21.0.0
    parameters:
      app-dir:
        default: '~/project/module-java'
        type: string
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: Unit Testing
          command: cd << parameters.app-dir >> && ./mvnw test
      - store_test_results: 
          path: << parameters.app-dir >>/target/surefire-reports
  update-module-version:
    docker:
      - image: cimg/openjdk:21.0.0
    parameters:
      app-dir:
        default: 'module-java'
        type: string
      publish-module-version:
        type: string
        default: ""
      publish-module:
        type: string
        default: ""
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Update Version"
          command: |
            cd << parameters.app-dir >>
            mvn versions:set -DnewVersion=<< parameters.publish-module-version >>
      - run:
          name: "Commit changes"
          command: |
            git commit --all -m "chore: Preparing for publication"
            git tag -a << parameters.publish-module >>/<< parameters.publish-module-version >>
            git push
            gut push origin << parameters.publish-module >>/<< parameters.publish-module-version >>
      - persist_to_workspace:
          root: .
          paths:
            - << parameters.app-dir >>

workflows:
  module_java_test:
    when:
      not: << pipeline.parameters.publish-module >>
    jobs:
      - checkout
      - test:
          requires:
            - checkout
  publish_module_java:
    when:
      equal: [ module-java, << pipeline.parameters.publish-module >> ]
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - update-module-version:
          publish-module-version: << pipeline.parameters.publish-module-version >>
          publish-module: << pipeline.parameters.publish-module >>
          requires: 
            - test




