# Config dedicated for module B
# All the resources must be prefixed with `module-b-` to avoid conflicts

version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:21.0.0
    parameters:
      app-dir:
        default: '~/project/module-java'
        type: string
    steps:
      - checkout
      - run: 
          name: Show java version
          command: java --version
      - run: 
          name: Unit Testing
          command: cd << parameters.app-dir >> && ./mvnw test
      - store_test_results: 
          path: << parameters.app-dir >>/target/surefire-reports
  publish-module:
    docker:
      - image: cimg/openjdk:21.0.0
    steps:
      - run:
          name: "Publish"
          command: "echo publish"

workflows:
  module_java_test:
    when:
      not: << pipeline.parameters.publish-module >>
    jobs:
      - test
  publish_module_java:
    when:
      equal: [ module-java, << pipeline.parameters.publish-module >> ]
    jobs:
      - test
      - publish-module



